

services:
  pi-agent: &default-agent
    image: pi-agent:${VERSION}
    build:
      dockerfile: Dockerfile
      context: ./docker/
      args:
        VERSION: ${VERSION}
        CHECKSUM: ${CHECKSUM}
    environment:
      PI_OFFLINE: 1
    volumes: &default-volumes
      - type: volume
        source: pi-data
        target: /root/.pi
    tty: true

  python-agent:
    <<: *default-agent
    image: pi-python-agent:${VERSION}
    build:
      dockerfile: Dockerfile.dev
      target: python-agent
      context: ./docker/
      args:
        VERSION: ${VERSION}

  go-agent:
    <<: *default-agent
    image: pi-go-agent:${VERSION}
    build:
      dockerfile: Dockerfile.dev
      target: go-agent
      context: ./docker/
      args:
        VERSION: ${VERSION}

volumes:
  pi-data:
