services:
  pi-agent:
    image: pi-agent:${VERSION}
    build:
      dockerfile: Dockerfile
      target: pi-agent
      context: ./docker/
      args:
        VERSION: ${VERSION}
        CHECKSUM: ${CHECKSUM}
    environment:
      PI_OFFLINE: 1
    tty: true
    volumes:
      - type: volume
        source: pi-data
        target: /root/.pi
      - type: bind
        source: ./projects
        target: /projects
    working_dir: /projects

  python-agent:
    image: pi-python-agent:${VERSION}
    extends:
      service: pi-agent
    build:
      target: python-agent

  go-agent:
    image: pi-go-agent:${VERSION}
    extends:
      service: pi-agent
    build:
      target: go-agent

volumes:
  pi-data: