services:
  pi-coding-agent:
    image: pi-coding-agent:${VERSION}
    build:
      dockerfile: Dockerfile
      context: .
      args:
        VERSION: ${VERSION}
        CHECKSUM: ${CHECKSUM}
    volumes:
      - type: volume
        source: pi-data
        target: /home/user/.pi
    tty: true

volumes:
  pi-data:
