ARG VERSION
FROM pi-coding-agent:${VERSION} as go-agent

USER root

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends golang && \
  rm -rf /var/lib/apt/lists/*

USER user


ARG VERSION
FROM pi-coding-agent:${VERSION} as python-agent

USER root

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y python3 python3-dev python3-pip && \
  rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:0.9.26 /uv /uvx /bin/

USER user