# Golang agent
ARG VERSION
FROM pi-agent:${VERSION} as go-agent

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends golang && \
  rm -rf /var/lib/apt/lists/*

# Python agent
ARG VERSION
FROM pi-agent:${VERSION} as python-agent

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y python3 python3-dev python3-pip && \
  rm -rf /var/lib/apt/lists/*

ARG UV_VERSION=0.10.6
COPY --from=ghcr.io/astral-sh/uv:${UV_VERSION} /uv /uvx /bin/
